name: Deploy via ftp

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: build-deploy

jobs:

  deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Upload service
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "Src"
          remoteDir: "."
